### ISSUE TITLE
Error: Browser is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by styfle** [vercel/og-image#123]
Running `vercel dev` prints the following error:

```
Error: Browser is not downloaded. Run "npm install" or "yarn install"
```

The workaround is to set `const isDev = true` during local development.

https://github.com/vercel/og-image/blob/7c697b8448fabc61eaad480f9891a22d60cada5f/api/index.ts#L6

**Comment by YIPG** [comment]
Hello, I've encountered the same error.

 It would be nice that NODE_ENV switches to 'production' if the server runs on correct locations...? 🤨
