### ISSUE TITLE
`.svg` output format

### ISSUE THREAD

**Issue by TooTallNate** [vercel/og-image#126]
It would be nice if there was an option to output to SVG 👍

**Comment by styfle** [comment]
We would have to use something besides puppeteer screenshot which only supports png and svg. 

https://github.com/puppeteer/puppeteer/blob/v5.2.1/docs/api.md#pagescreenshotoptions

Also, need to research if existing social networks will accept svg as the og image.

**Comment by TooTallNate** [comment]
Ahhh right. Would probably need to be refactored to use `node-canvas` or something else that supports svg output.

**Comment by TooTallNate** [comment]
Also, I'm not sure about social networks + svg, but the reason I made this issue is because I'm (ab)using this service for use in GitHub readmes ([example](https://github.com/TooTallNate/vercel-deno/blob/2637ae08e68b367f36c7d8a54f3e67e98cbf737e/README.md)).

**Comment by olafghanizadeh** [comment]
og (opengraph) does not support SVG – would be nice if it did in the future though.

**Comment by styfle** [comment]
You can use https://github.com/vercel/satori directly to generate SVG.
