### ISSUE TITLE
Allow option for a subtitle

### ISSUE THREAD

**Issue by TooTallNate** [vercel/og-image#128]
It would be cool to add an option for a subtitle that would be rendered below the main title in a color that complements the main title (i.e. a lighter gray that matches the `+` symbol).

**Comment by styfle** [comment]
Do we need this for an upcoming blog post? Is there an existing design we can base it on?

**Comment by TooTallNate** [comment]
Not for a blog post per say, but for personal usage.

**Comment by styfle** [comment]
I'm going to close this one since it can be forked and added, but doesn't need to be in the main repo here 👍
