### ISSUE TITLE
Additional image does not work in Next.js tutorial

### ISSUE THREAD

**Issue by MrHertal** [vercel/og-image#141]
Hi,

I encounter an issue when adding a second image. It works well when I paste the generated URL directly in the browser:

<img width="1541" alt="snap1" src="https://user-images.githubusercontent.com/11944221/100742469-21a13700-33db-11eb-882b-224e9485ff2e.png">

Then I paste the generated URL in my Next.js app (following the official [tutorial](https://nextjs.org/learn/basics/assets-metadata-css/polishing-layout)):

```tsx
        <meta
          property="og:image"
          content={`https://og-image.now.sh/${encodeURI(
            siteTitle
          )}.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fvercel-triangle-black.svg&images=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fremojansen%2Flogo.ts%40master%2Fts.svg`}
        />
```

This renders the following HTML code:

```html
<!DOCTYPE html>
<html>
<head>
<style data-next-hide-fouc="true">body{display:none}</style>
<noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript>
<meta name="viewport" content="width=device-width"/>
<meta charSet="utf-8"/>
<link rel="icon" href="/favicon.ico"/>
<meta name="description" content="Learn how to build a personal website using Next.js"/>

<meta property="og:image" content="https://og-image.now.sh/Next.js%20Sample%20Website.png?theme=light&amp;md=1&amp;fontSize=100px&amp;images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fvercel-triangle-black.svg&amp;images=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fremojansen%2Flogo.ts%40master%2Fts.svg"/>

<meta name="og:title" content="Next.js Sample Website"/>
```

Then I check the `go:image` URL in the browser I get the following:

<img width="1526" alt="snap2" src="https://user-images.githubusercontent.com/11944221/100743282-67123400-33dc-11eb-9806-48c13ecbe89f.png">

Additional image is gone.

It seems to be a bad URL encoding when HTML is rendered by Next.js.

I was not sure about creating the issue in this repo or in Next.js repo. If you think this should not be here, I will create an issue in Next.js repo.

Thanks for your help.

**Comment by styfle** [comment]
The url is encoded correctly.

Try validating your website here: https://cards-dev.twitter.com/validator

**Comment by MrHertal** [comment]
You are right, the two images are well displayed on the validator.

I should not have tried to validate the image myself on the browser. It confused me.

Thanks!
