### ISSUE TITLE
Investigate replacing puppeteer with smaller alternative

### ISSUE THREAD

**Issue by styfle** [vercel/og-image#148]
We are bumping up against the 50MB limit when upgrading dependencies since chromium continues to get larger.
This was discovered in a PR that was bumping dependencies: #147 
We could try using a different tool to reduce the size.

### HTML => PNG

The developer authors HTML and we convert to PNG with a browser, for example:

- `puppeteer-core` + `chrome-aws-lambda` is approximately 55MB (and growing)
- `playwright-core` + `playwright-aws-lambda` is approximately 52MB (and growing)
- [`wkhtmltoimage`](https://github.com/wkhtmltopdf/wkhtmltopdf) is approximately 45MB, see [how do I use AWS Lambda](
https://wkhtmltopdf.org/downloads.html#how-do-i-use-it-in-aws-lambda)
  - This looks like its no longer maintained
- [NetSurf](https://www.netsurf-browser.org/) is approximately 8MB
- [Other lightweight browsers](https://en.wikipedia.org/wiki/Comparison_of_lightweight_web_browsers) are worth investigating

### SVG => PNG

The developer authors SVG and we convert to PNG with a library, for example:

- [`sharp`](https://www.npmjs.com/package/sharp) is approximately 20MB
  - #181 
- [`@resvg/resvg-js`](https://www.npmjs.com/package/@resvg/resvg-js) is approximately 3MB
  - #183 
- [`@napi-rs/canvas`](https://www.npmjs.com/package/@napi-rs/canvas) is approximately 19MB [demo](https://github.com/Brooooooklyn/vercel-canvas) 
  - #182

**Comment by JavierMartinz** [comment]
I'm having this problem too and I cannot deploy it to Vercel. I saw [here](https://github.com/vercel/vercel/issues/4739#issuecomment-803428521) that a workaround would be moving the JS from `pages/api/` to `api/`, but in that case the URL wouldn't be reachable anymore.

**Comment by styfle** [comment]
> in that case the URL wouldn't be reachable anymore

What does that mean? Using [`api/`](https://github.com/vercel/og-image/blob/main/api/index.ts) is how this repo works. Have you tried cloning this repo and using the same dependency version from [`package.json`](https://github.com/vercel/og-image/blob/84e305d4946227ce8383988911f419db57c1cc3e/package.json#L10-L12)?

**Comment by marklawlor** [comment]
@styfle Indeed that comment is out of place for this repo, but it would be greatly appreciated if you could take your time to answer some of the questions in the linked issue. 

It appears that Vercel imposes a _combined_ 50mb issue on all NextJS `/pages/api` functions, but allows a 50mb _individual_ limit for functions in `/api`. This seems counter intuitive to the [Vercel limits documentation](https://vercel.com/docs/platform/limits#serverless-function-size) as `@next/bundle-analyzer` reports `/pages/api` as individual functions.

For example if you have three functions that compile to 45mb, 5mb, 2mb. If using NextJS you will not be able to deploy onto Vercel, however this will work for non-NextJS projects.

I hope that explains @JavierMartinz's intent and again it would be awesome if you could take the time to post a clarifying response in the [linked issue](https://github.com/vercel/vercel/issues/4739)

**Comment by styfle** [comment]
@marklawlor The linked issues were fixed so perhaps you are hitting a different corner case.

If you could create a new issue with an example repo that fails, then we can take a look, thanks!

**Comment by marklawlor** [comment]
@styfle Both the linked issue and discussion continue after being marked as resolved and contain the example repo that fails (updated after the patch was released)

For example https://github.com/vercel/vercel/discussions/4013#discussioncomment-3467 and its follow up comment https://github.com/vercel/vercel/discussions/4013#discussioncomment-3604

This is the exact issue I am receiving.

**Comment by jongold** [comment]
+1 - I love the approach of this repo but running into these issues getting it running in Next.js on Vercel

**Comment by leerob** [comment]
@jongold we're testing a few approaches right now! Check out the latest pulls https://github.com/vercel/og-image/pulls

**Comment by AmreshSinha** [comment]
You can also give [node-canvas](https://github.com/Automattic/node-canvas) a try

**Comment by yisibl** [comment]
| Engine     | [resvg & resvg-js](https://github.com/yisibl/resvg-js) | [sharp & librsvg](https://gitlab.gnome.org/GNOME/librsvg) | [skr-canvas & skia](https://github.com/Brooooooklyn/canvas/)                                       | 
| -------- | --------------------------------------------- | ------------------------------------------------- | -------------------------------------------------------------------------------------- |
| language | Rust+JS                                          | Rust/C++                                              | Rust/C++                                                                                    | 
| Features     | Lightweight and fast. SVG1.1 best compatibility              | Full CSS3 selector support, `<text>` support is poor              |Less support for SVG and CSS selectors|

**Comment by weolar** [comment]
hi, you can use miniblink: https://github.com/weolar/miniblink49

**Comment by styfle** [comment]
We decided that embedding a browser is not a sustainable solution. 

So we built an alternative solution to convert HTML/CSS to PNG. 

Check out https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images
