### ISSUE TITLE
Can't  run locally with command "vercel dev" or deploy with command "vercel"

### ISSUE THREAD

**Issue by Co9xs** [vercel/og-image#150]
I am referring to [Deploy your own](https://github.com/vercel/og-image#deploy-your-own) for the setup.
However, when I tried to run localy with  "vercel dev" and answer a few questions, I get the following error.
`Error! queryA EREFUSED api.vercel.com`

## How to Reproduce
- Fork [vercel/og-image](https://github.com/vercel/og-image)
- Clone repo to my local machine with `git clone URL_OF_FORKED_REPO_HERE`
- Change directory with `cd og-image`
- Remove all configuration inside vercel.json besides rewrites
- Run  `vercel dev` and answering a few questions, I get the following error!
`Error! queryA EREFUSED api.vercel.com`
<img width="364" alt="スクリーンショット 2021-03-09 14 17 23" src="https://user-images.githubusercontent.com/57798045/110422181-2e23e280-80e2-11eb-92d8-1dad995bfbec.png">

I have confirmed that vercel is installed globally and logged in correctly.
Thanks for reading.

**Comment by styfle** [comment]
There's a similar issue reported here: https://github.com/vercel/vercel/issues/3705#issuecomment-599527077

You can try clearing npm / yarn cache and installing vercel again.

```
npm uninstall -g vercel
npm cache clean
npm install -g vercel
```

**Comment by Co9xs** [comment]
Thank you for your quick answer.
I have tried the following command but I get the same error.

> npm uninstall -g vercel
> npm cache clean --force
> npm install -g vercel

**Comment by Co9xs** [comment]
Sorry for the late reply.
I tried a different network and it worked without any errors :)
