### ISSUE TITLE
Can't Deploy to Vercel Pro Anymore

### ISSUE THREAD

**Issue by sampoder** [vercel/og-image#153]
I am aware of how to fix this but the docs will likely need changing. View screenshot.

Thank you and best,

Sam

<img width="673" alt="Screenshot 2021-04-03 at 3 26 48 PM" src="https://user-images.githubusercontent.com/39828164/113471752-22cd9800-9491-11eb-9a90-c95946d3ab11.png">

**Comment by leerob** [comment]
For posterity, you can change `regions` in your `vercel.json` to whichever region you prefer. But yes, I agree docs should be updated.

**Comment by sampoder** [comment]
yep! thank you!
