### ISSUE TITLE
Tamil language is not supported

### ISSUE THREAD

**Issue by bnainar** [vercel/og-image#157]
தமிழ் (`ta_IN`)
![IMG_20210407_075449](https://user-images.githubusercontent.com/59839368/113801546-ae3b7780-9776-11eb-8ba9-88d23c94ea8b.jpg)

**Comment by styfle** [comment]
Seems like Inter font doesn't support Tamil, unfortunately https://rsms.me/inter/

You can try submitting an issue here: https://github.com/rsms/inter

**Comment by bnainar** [comment]
What about an option to change font, so that we can select one supports it

**Comment by styfle** [comment]
We're not planning to add multiple fonts to this repo, but you can fork this repo and change the font for your own project.

Learn how to [Deploy your own](https://github.com/vercel/og-image#deploy-your-own)

**Comment by bnainar** [comment]
Wow. That's even  cool. Thanks
