### ISSUE TITLE
Unable to deploy on Vercel using the deploy button on the repo

### ISSUE THREAD

**Issue by shivkanthb** [vercel/og-image#158]
I hit the deploy button on the readme and followed the wizard but at the end, when I hit deploy, I get the following error
![Screen Shot 2021-04-09 at 12 12 29 AM](https://user-images.githubusercontent.com/3232159/114143040-80fede80-98c8-11eb-82f3-46a58a4f1a81.png)

**Comment by shivkanthb** [comment]
Found the reason: 
vercel.json has
```
"memory":  3008
```
I guess it would be good to mention that in the readme if someone is deploy this on their personal plan

**Comment by styfle** [comment]
Its step 5 in the readme 🙂 

> 5. Remove all configuration inside `vercel.json` besides `rewrites`

**Comment by shivkanthb** [comment]
Yep noticed that. Is it possible to update that if someone goes via the vercel deploy button on the readme?

**Comment by styfle** [comment]
Unfortunately no, the Deploy button can't modify files.

However, you can fork the repo, change the file yourself, and use https://vercel.com/new to deploy the fork.
