### ISSUE TITLE
How to deploy `og-image` on Netlify?

### ISSUE THREAD

**Issue by iamrajiv** [vercel/og-image#172]
## Description

I want to deploy `https://github.com/vercel/og-image` on Netlify. I tried deploying and it deployed successfully but it is not loading anything.

https://og-image.netlify.app

**Comment by styfle** [comment]
You'll probably need to convert the API from [Vercel Functions](https://vercel.com/docs/concepts/functions/introduction) to [Netlify Functions](https://www.netlify.com/products/functions/) but I haven't tried it

**Comment by sasigume** [comment]
Seems too late but I finally figured out how to deploy on Netlify.

## Codes

### netlify.toml

```toml
[build]
  command = "yarn build"
  publish = "public"

[functions]
  directory = "api"
  external_node_modules = ["chrome-aws-lambda"]
```

### api/index.ts

```ts
import { parseRequest } from './_lib/parser';
import { getScreenshot } from './_lib/chromium';
import { getHtml } from './_lib/template';
import { Handler } from '@netlify/functions';
import { Buffer } from 'buffer';

const isHtmlDebug = process.env.OG_HTML_DEBUG === '1';

export const handler: Handler = async (event, ctx) => {
  const isDev = !ctx.clientContext?.custom?.netlify;
  try {
    const parsedReq = parseRequest(event);
    const html = getHtml(parsedReq, isHtmlDebug);
    if (isHtmlDebug) {
      return {
        statusCode: 200,
        headers: {
          'Content-Type': 'text/html',
          'Cache-Control': '',
        },
        body: html,
      };
    }
    const { fileType } = parsedReq;
    const file = await getScreenshot(html, fileType, isDev);
    return {
      statusCode: 200,
      headers: {
        'Content-Type': `image/${fileType}`,
        'Cache-Control': `public, immutable, no-transform, s-maxage=31536000, max-age=31536000`,
      },
      body: Buffer.from(file).toString('base64'),
      isBase64Encoded: true,
    };
  } catch (e) {
    console.error(e);
    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'text/html',
        'Cache-Control': '',
      },
      body: '<h1>Internal Error</h1><p>Sorry, there was a problem</p>',
    };
  }
};
```

The tricky part is that `isDev` needs to be tweaked for Netlify lambda because `AWS_REGION` is also set when run with Netlify CLI on local. I tested with several env variables but even `NODE_ENV` is not set on Netlify lambda environment.

### package.json

```diff json
-  "build": "tsc -p api/tsconfig.json && tsc -p web/tsconfig.json"
+. "build": "tsc -p api/tsconfig.json --noEmit && tsc -p web/tsconfig.json",
```

`api/dist` directory is not needed because Netlify natively supports TypeScript. So we do only type-check here.

**Comment by BrownieBits** [comment]
I am having trouble deploying this. the landing page deploys fine and I can get there without issue through Netlify. When trying to get it to pull an image is where i have the issue and not sure where i went wrong. It doesnt seem to be triggering the functions.

In the `/api/_lib/parser.ts` i have this
```
import { Event } from '@netlify/functions/dist/function/event';
import { parse } from 'url';
import { ParsedRequest, Theme } from './types';

export function parseRequest(req: Event) {
    const { pathname, query } = parse(req.path.replace('/.netlify/functions/index', '') || '/', true);
    const { fontSize, images, widths, heights, theme, md } = (query || {});
```
but am getting an error that parse is deprecated. so my first thought is that it is not doing that replace line of code which then doesnt trigger the function.

is there more configuration I should use other than what is above?
