### ISSUE TITLE
helper.createServerWithHelpers is not a function

### ISSUE THREAD

**Issue by julianfox** [vercel/og-image#178]
Hello,
I followed the deploy your own section and I got this error on my local env:
Unhandled rejection: TypeError: helper.createServerWithHelpers is not a function

The interface works well but the image does not display, the problem seems to be on the API side. I tried to find a solution without success. any ideas ?

**Comment by styfle** [comment]
Did you modify any code or just deploy it as-is?

It would be great if you could share the source code, thanks!

**Comment by eccentricdz** [comment]
Hello I am getting the same error when trying to test my serverless functions locally using `vercel dev`.

Here is the source code:
https://github.com/eccentricdz/finscreen-serverless-api

**Comment by styfle** [comment]
I'm getting seeing a different error when running that repo:

> ERROR	Unable to connect to the MongoDB client: MongoParseError: URI malformed, cannot be parsed

**Comment by eccentricdz** [comment]
I was able to resolve my issues by using `vercel@canary`, although I am not entirely sure of the root cause. Thanks for looking into it.
