### ISSUE TITLE
How can we start it locally

### ISSUE THREAD

**Issue by ats1999** [vercel/og-image#186]

**Comment by styfle** [comment]
Yep, it’s step 6 in the readme.md

Also checkout contributing.md

**Comment by ats1999** [comment]
I think, i can not start it on hobby plan

**Comment by styfle** [comment]
Are you seeing an error message? Running “vercel dev” should behave the same on all plans.

**Comment by ats1999** [comment]
On running locally as mentioned in contributing.md

![Screenshot from 2022-01-16 21-43-54](https://user-images.githubusercontent.com/54087826/149668109-b51511e5-92c0-4b9f-a10d-7a1563fca7aa.png)

**Comment by styfle** [comment]
You need to modify vercel.json as mentioned in the docs
