### ISSUE TITLE
Would you consider allowing the first image to be custom ?

### ISSUE THREAD

**Issue by bokub** [vercel/og-image#194]
Hi,

In this code, I see that you're not allowing the first image to be a custom URL.

https://github.com/vercel/og-image/blob/84e305d4946227ce8383988911f419db57c1cc3e/api/_lib/parser.ts#L61-L63

If I want to use a custom image, the easiest option for me is to:
- fork this repo
- edit `vercel.json` to allow deployment on a free account
- remove these 3 lines
- deploy my fork on Vercel

I don't have a problem doing this, but it may be a painful process for some people, and I feel like it's a waste of resource because this project will probably be deployed dozens of times just to bypass this limitation.

So my question is: **Would you consider allowing the first image to be custom ?** Why did you forbid it it the first place?

Thanks!

**Comment by styfle** [comment]
Hi Boris,

This is expected and forking is the desired behavior. 

This project is an example to show you how to build your own generator.

Every project should have a different background, different images, etc to match the brand of your website.

Ideally, we would make the deploy button one click so you don’t need to change config and we plan to do that in future, thanks!

**Comment by Nithur-M** [comment]
Does deploying my own version requires a pro plan?
I get this error:` Serverless Functions are limited to 1024 of memory (in steps of 64) for personal accounts (Hobby plan). To increase, create a team (Pro plan).`
