### ISSUE TITLE
How much does it cost to host on vercel

### ISSUE THREAD

**Issue by ats1999** [vercel/og-image#195]
Hi, @vercel-infra 
I  would like to know how much does it cost to host on vercel if my application receives a 1K request per day.

**Comment by bokub** [comment]
Hi,

The free plan (A.K.A hobby) is not limited and should be enough for your needs

https://vercel.com/docs/concepts/limits/overview

**Comment by ats1999** [comment]
Thanks

**Comment by styfle** [comment]
Also see the [Fair Use Policy](https://vercel.com/docs/concepts/limits/fair-use-policy)
