### ISSUE TITLE
Does this generate images on each request

### ISSUE THREAD

**Issue by ats1999** [vercel/og-image#196]
Hi, i would like to know that does it generate a new image on each request. 

How It can be  cost optimized?

**Comment by bokub** [comment]
No it doesn't.
Each image is generated only once, saved in cache, then served from the cache:

![image](https://user-images.githubusercontent.com/17952318/155552505-9bc5a1fb-34f6-422a-af3e-b9ed1301fa5b.png)

**Comment by ats1999** [comment]
Where does it get cached?

**Comment by ats1999** [comment]
Thanks
