### ISSUE TITLE
serverless function exceeds maximum size limit of 50mb

### ISSUE THREAD

**Issue by linojon** [vercel/og-image#205]
Hello, i borrowed your code and am trying to use the `getScreenshot` function directly in my project to render html into a png image.

## When i run `yarn dev` (on Windows 11) i get the following error:

```
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (991974).
    at ChromeLauncher.launch (file:///D:/Documents/JavascriptProjects/opportunity/node_modules/puppeteer-core/lib/esm/puppeteer/node/Launcher.js:80:23)
```

Per your options.ts, i have confirmed i do have chrome.exe installed at `'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'`

Likewise, i get the same error when i run `vercel dev` 

Running install says i'm up-to-date.
I tried a few things found googling, including cd into the nodemodules/puppeteer-core folder and running npm install from there, But it gets a build error

I realize this is probably a puppeteer problem but maybe you can help?

## When i deploy my app with the `getScreenshot` call to Vercel, i get the following error during build 

```
Error: The Serverless Function "api/oppscore/[id]/image.png" is 64.5mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
```

**Comment by linojon** [comment]
hi.  re second issue 
OK i tried using an older version of chrome-aws-lambda v1.6.3, and that gets past the build error. 
Now when i try to get an image i see the following in my vercel logs

```
[GET] /subjects/4/image.png
16:40:39:70
% process.platform % linux
GET /api/oppscore/4/image.png
Error: Failed to launch the browser process!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (file:///var/task/node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:218:20)
    at Interface.<anonymous> (file:///var/task/node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:208:56)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-05-19T20:41:41.257Z 00454114-66ae-49ab-996d-ec30afb47295 Task timed out after 60.07 seconds
```

**Comment by styfle** [comment]
The 50mb issue is know. See https://github.com/vercel/og-image/issues/148

You’ll need to use the same package.json and lock file to use the older version

**Comment by linojon** [comment]
50mb seems like an arbitrary number. Why not just raise the size limit?

**Comment by styfle** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

> The following quotas apply to function configuration, deployment, and execution. They cannot be changed.
> 
> Deployment package (.zip file archive) size: 
> - 50 MB (zipped, for direct upload)
> - 250 MB (unzipped)
