### ISSUE TITLE
Can't start dev server in freshly forked repo

### ISSUE THREAD

**Issue by kilinkis** [vercel/og-image#207]
Hi guys, thanks for this awesome tool.

I just forked the repo and followed the steps in the [Readme](https://github.com/vercel/og-image#readme), to run it locally (also checked the [contrib](https://github.com/vercel/og-image/blob/main/CONTRIBUTING.md) Readme).
But I get this error:

```
➜  og-image git:(main) ✗ vercel dev                  
Vercel CLI 25.0.0
> Creating initial build
Running "yarn run build"
yarn run v1.17.0
$ tsc -p api/tsconfig.json && tsc -p web/tsconfig.json
✨  Done in 5.34s.
Error! Detected Build Output v3 from the "build" script, but this Deployment is not using `vercel build`.
Please set the `ENABLE_VC_BUILD=1` environment variable.
```

So I also tried `ENABLE_VC_BUILD=1 vercel dev` and got the same error

my node -v is 14.13.0

Any clues on what could be happening?

**Comment by styfle** [comment]
Can you share the forked repo source code?

It sounds like there might be a `.vercel/output/config.json` file being created

https://github.com/vercel/vercel/blob/3aa2fbbb535068ae5111fd9b8b5f9337d1828bac/packages/static-build/src/utils/build-output-v3.ts#L13-L25

**Comment by styfle** [comment]
I see the problem: This can happen if you run `vercel build` followed by `vercel dev`.

Thanks for reporting, we'll get this fixed in https://github.com/vercel/vercel/pull/7927

**Comment by kilinkis** [comment]
ah yes, I think that could've been the case @styfle! thanks for fixing this!

**Comment by styfle** [comment]
In the meantime, you can `rm -rf .vercel/output` and that will fix it 👍
