### ISSUE TITLE
UI doesn't work, outputs code instead.

### ISSUE THREAD

**Issue by kilinkis** [vercel/og-image#208]
This happens on local and also the deployed version:
see here: https://jsb-og-image.vercel.app/

the UI is not showing, and js code is being outputed instead.

The image generation works well.

Any ideas what is happening here? here's the repo just in case: https://github.com/kilinkis/og-image

thanks!

**Comment by styfle** [comment]
It looks like you made changes to the project settings. If you disable the overrides and use the default settings, it should work as expected.

**Comment by kilinkis** [comment]
do you refer to [these](https://github.com/kilinkis/og-image/commit/41b1e515fc543d7eeac145532d83e69a9f1f7159#diff-a3265310f552fb66876e8bfe8809737e59e5ba946bdf39138b44d9baf4e21240) changes @styfle? 
I reverted all the other changes now and still happens.

And those changes in the commit in vercel.json are the ones mentioned in the readme file 🤔

**Comment by styfle** [comment]
Visit https://vercel.com/dashboard

Click the project

Click settings

Then you’ll see that there are overrides. Those should be disabled so the default Build Command and Output Directory are used.

**Comment by kilinkis** [comment]
amazing man, thanks, works now!
