### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "14.x"

### ISSUE THREAD

**Issue by Nithur-M** [vercel/og-image#218]
When I run `vercel dev`, I am getting this error:
`The engine "node" is incompatible with this module. Expected version "14.x". Got "16.15.0"`

Should I downgrade my node version?

**Comment by styfle** [comment]
Yes, it only works with Node.js 14

See upstream issue here https://github.com/alixaxel/chrome-aws-lambda/pull/274

**Comment by leerob** [comment]
Closing in favor of https://github.com/vercel/og-image/issues/226
