### ISSUE TITLE
Twitter image needs to be one word

### ISSUE THREAD

**Issue by shinokada** [vercel/og-image#237]
When I use it for `twitter:image`, `title` needs to be one word without a space.

This doesn't work with Twitter.

```
<meta name="twitter:image" content="https://open-graph-vercel.vercel.app/api/flowbite-svelte?title=Speed Dial">
```

This works.

```
<meta name="twitter:image" content="https://open-graph-vercel.vercel.app/api/flowbite-svelte?title=Speed-Dial">
```

![image](https://user-images.githubusercontent.com/147320/202881125-d54b6453-9ded-4185-adc4-ddc69c338fe1.png)

What is the best way to use multiple words without hyphenes?

**Comment by styfle** [comment]
Try `%20`, like this:

```html
<meta name="twitter:image" content="https://open-graph-vercel.vercel.app/api/flowbite-svelte?title=Speed%20Dial">
```

See the README for another example.

**Comment by alexrabin** [comment]
Adding the %20 helped me! Thank you!

> Try `%20`, like this:
> 
> ```
> <meta name="twitter:image" content="https://open-graph-vercel.vercel.app/api/flowbite-svelte?title=Speed%20Dial">
> ```
> 
> See the README for another example.
