### ISSUE TITLE
How to return a 401 error on one endpoint of these?

### ISSUE THREAD

**Issue by kevinfaveri** [vercel/og-image#238]
I have created a vercel OG endpoint, and want to return a 401 error with a JSON message for the specific error. Anyway to do it?

**Comment by kevinfaveri** [comment]
There is no res to return, it seems, as the second param next to req is a NextFetchEvent, that obviously does not have the capabilities for returning stuff as expected

**Comment by styfle** [comment]
You can return `new Response()`

See the Edge Runtime api here: https://nextjs.org/docs/api-reference/edge-runtime
