### ISSUE TITLE
Investigate font loading

### ISSUE THREAD

**Issue by styfle** [vercel/og-image#70]
It might be faster to load fonts with the new [font api](https://github.com/alixaxel/chrome-aws-lambda#fonts) instead of reading the file and then injecting css for reach request.

```js
const chromium = require('chrome-aws-lambda');
await chromium.font('https://example.com/googlei18n/noto-emoji/fonts/NotoColorEmoji.ttf');
```

Related issue: https://github.com/alixaxel/chrome-aws-lambda/issues/16

**Comment by leerob** [comment]
Closing for https://github.com/vercel/og-image/issues/226
